"""initial_migration

Revision ID: 341875ecf7b7
Revises: 
Create Date: 2018-09-29 19:09:08.373955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341875ecf7b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('from_kiosk_location_id', sa.Integer(), nullable=True),
    sa.Column('to_kiosk_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_kiosk_location_id'], ['kiosk_locations.id'], ),
    sa.ForeignKeyConstraint(['to_kiosk_location_id'], ['kiosk_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_distances')
    op.drop_table('kiosk_locations')
    # ### end Alembic commands ###
